### ISSUE TITLE
Missing pause functionality

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-animated-cards-changelog#2]
**Short description of the bug:** this "marquee" like component is [not accessible](https://www.w3.org/TR/WCAG20/#time-limits-pause)
**Steps to reproduce the bug:** animated cards play automatically with no ability to pause the animation
**Browser + Operating system:** NA

Is it possible to add a variation or an option to add a simple play/pause button or icon? For example: 
![image](https://user-images.githubusercontent.com/16456162/88979202-d3dabd80-d286-11ea-8c72-eaa385fb55a6.png)

**Comment by claudia-romano** [comment]
Hi Emily, thanks for the suggestion. We have pushed an updated version of the component that includes a control button:
https://codyhouse.co/ds/components/app/animated-cards

Cheers!
