### ISSUE TITLE
Draggable & Stop Autoplay on Hover (Enhancement)

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-animated-cards-changelog#3]
Is it possible to enhance this component with:

– Draggable like here: https://codyhouse.co/ds/components/app/draggable-image-gallery
– Stop Autoplay on mousehover

🙏

**Comment by claudia-romano** [comment]
Hi there,
we pushed an updated version of the component that includes the option of pausing the animation on hover. You can find additional info on the component [Info page](https://codyhouse.co/ds/components/info/animated-cards).

As for the drag, this is not an option we plan on including at the moment. You may consider using the [Draggable Image Gallery](https://codyhouse.co/ds/components/info/draggable-image-gallery) or a [Carusel](https://codyhouse.co/ds/components/app/carousel).

Cheers!
